name: production

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

env:
  PROJECT_ID: hackspree
  APP_NAME: lunar-workshop-example-app

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy
        run: gcloud run deploy ${{ env.APP_NAME }}-dev --image asia.gcr.io/$PROJECT_ID/${{ env.APP_NAME }}:${{ inputs.version }} --region asia-southeast1 --platform managed --allow-unauthenticated --max-instances 1 --port 3000

