name: staging

on:
  push:
    tags:
      - v*

env:
  PROJECT_ID: hackspree
  APP_NAME: lunar-workshop-example-app

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Get CONTAINER_IMAGE
        run: echo "CONTAINER_IMAGE=asia.gcr.io/$PROJECT_ID/${{ env.APP_NAME }}:${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Login gcloud docker
        run: gcloud auth configure-docker -q

      - name: Docker build
        run: docker build -t $CONTAINER_IMAGE .

      - name: Release
        run: docker push $CONTAINER_IMAGE
    outputs:
      CONTAINER_IMAGE: ${{env.CONTAINER_IMAGE}}
  
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-18.04
    needs:
      - build
    steps:
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy
        run: gcloud run deploy ${{ env.APP_NAME }}-staging --image ${{needs.build.outputs.CONTAINER_IMAGE}} --region asia-southeast1 --platform managed --allow-unauthenticated --max-instances 1 --port 3000

